default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: postgres
  password: password
  host: localhost

development:
  <<: *default
  database: planyourplantsapi_development

test:
  <<: *default
  database: planyourplantsapi_test
  username: postgres
  password: password
  host: localhost

production:
  <<: *default
  database: planyourplantsapi_production
